name: Create Jira Issue from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run local Rust Jira Action
        uses: UHeeJoon/jira-actions@main
        with:
          github_issue_title: ${{ github.event.issue.title }}
          github_issue_body: ${{ github.event.issue.body }}
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ORG_NAME: ${{ secrets.JIRA_ORG_NAME }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          
          JIRA_EMAIL: ${{ github.event.issue.user.email }}
