name: Create Jira Issue from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Run local Rust Jira Action
        uses: UHeeJoon/jira-actions@v1.0.0
        env:
          ISSUE_TITLE:  ${{ github.event.issue.title }}
          ISSUE_BODY:  ${{ github.event.issue.body }}
        
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ORG_NAME: ${{ secrets.JIRA_ORG_NAME }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          
          JIRA_EMAIL: ${{ github.event.issue.user.email }}
